"""create_ai_tables

Revision ID: 4a62de39330e
Revises: 
Create Date: 2026-03-17 17:55:34.318770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a62de39330e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('scores_json', sa.JSON(), nullable=True),
    sa.Column('overall_index', sa.Float(), nullable=True),
    sa.Column('goal_type', sa.String(length=20), nullable=True),
    sa.Column('alignment_level', sa.String(length=20), nullable=True),
    sa.Column('alignment_source', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('reformulation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_generated_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('quarter', sa.String(length=2), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('goals_json', sa.JSON(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_generated_goals')
    op.drop_table('ai_evaluations')
    # ### end Alembic commands ###
